version: '3'

services:

  app:
    image: 451712634800.dkr.ecr.ap-south-1.amazonaws.com/sample-devops-app:latest # Trigger pipeline

    container_name: sample-app

    ports:
      - "3000:3000"

  prometheus:
    image: prom/prometheus

    container_name: prometheus

    ports:
      - "9090:9090"

    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana

    container_name: grafana

    ports:
      - "3001:3000"

    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.49.1
    container_name: cadvisor
    environment:
      - DOCKER_API_VERSION=1.45
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /var/lib/docker/:/rootfs/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    devices:
      - /dev/kmsg
    command:
      - '--enabled_container_env=containerd,systemd,raw'
      - '--containerd=/var/run/containerd/containerd.sock'

