---
# ─────────────────────────────────────────────────────────────────────────────
#  Kubernetes Namespace
# ─────────────────────────────────────────────────────────────────────────────
apiVersion: v1
kind: Namespace
metadata:
  name: immerverse
  labels:
    app: immerverse-cicd
    managed-by: jenkins
